@startuml
'https://plantuml.com/class-diagram

class Estacion {
numero: String
    operacion: Operacion
    funcion: Funcion
}

enum Operacion {
    INGRESO,
    EGRESO,
    GENERACION
}

class Funcion {
    descripcion: String

}
class ProcesadorLoteEnEstacion {
    recibirDatos(Datos DTO): PasoLoteEstacion
}

class PasoLoteEstacion {
    estacion: Estacion
    lote: Lote
    facheHora: LocalDateTime

}
class Lote {
    productos: List<Producto>
    estacionesRecorridas: List<Estacion>
    idOrden: String
    cantidadEsperada: Integer
    cantidadProducida: Integer
    fechaHoraInicio: LocalDateTime
    fechaHoraFin: LocalDateTime
}

class Evento {
    nombre: String
    fechaHora: LocalDateTime
    registradoManualmente: LocalDateTime
    lotesVinculados: List<Lote>
    estacionVinculada: Estacion
    merma :Merma
}
class Merma {
cantidadMermas: Integer
    unidadMedicionMermas: UnidadMedicion
}
class UnidadMedicion {
    nombre: String
}

class ReglaAlerta {
    estacion: Estacion
    porcentajeMerma: Double
    operacionAsociada: Operacion
    reglaDefinidaPor: String
}

class NotificadorAlerta {
    + notificarAlerta(ReglaAlerta reglaIncumplida): void
}

class GeneradorReporte {
    +calcularBalanceMasa(estacion)
}

Estacion --> Operacion
Estacion --> Funcion
Lote --> Estacion
Lote --> Producto
Evento --> Lote
Evento --> UnidadMedicion
NotificadorAlerta ..> ReglaAlerta
ProcesadorLoteEnEstacion ..> Lote
ReglaAlerta --> Operacion
PasoLoteEstacion  --> Estacion
PasoLoteEstacion  --> Lote
Evento --> Merma
@enduml